apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8070
          name: http
          protocol: TCP
      volumeMounts:
        - name: work-dir
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: install
      image: ubuntu:24.04
      command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y wget ca-certificates && \
          wget -O /work-dir/index.html https://raw.githubusercontent.com/sudheerduba/initContainer_demo/main/index.html
      volumeMounts:
        - name: work-dir
          mountPath: /work-dir



  volumes:
    - name: work-dir
      emptyDir: {}
