apiVersion: v1
kind: Pod
metadata:
    name: robin-pod
    labels:
        app: robin-app
        env: dev
        version: v1.0.0
spec:
    containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
              hostPort: 8090
              protocol: TCP
          env:
            - name: USERNAME
              value: "admin"
          volumeMounts:
            - name: nginx-config
              mountPath: "/usr/share/nginx/html"
    volumes:
      - name: nginx-config
        emptyDir: {}
