apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: nginx 
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: ENV_TYPE
          valueFrom:
            configMapRef:
              name: myconfig
              key: ENV_TYPE
              
              
