apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
    - name: nginx 
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: myconfig
          mountPath: /etc/config
      envFrom:
        - configMapRef:
            name: myconfig
