apiVersion: v1
kind: PersistentVolume
metadata:
    name: nginx-vol-01
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
