apiVersion: v1
kind: PersistentVolume
metadata:
    name: nginx-vol-01
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    nfs:
        path: /mnt/nfs/nginx-01
        server: 192.168.122.131
        type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nginx-vol-02
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    nfs:
        path: /mnt/nfs/nginx-02
        server: 192.168.122.131
        type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nginx-vol-03
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    nfs:
        path: /mnt/nfs/nginx-03
        server: 192.168.122.131
        type: DirectoryOrCreate
