apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: mysecret
