apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-demo
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80  # Expose port 80 on the service --> anyport no. user defined
      targetPort: 80  # nginx listens on port 80
  type: ClusterIP
