apiVersion: v1
kind: Pod
metadata:
  name: pod-tls
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: tls-sec
          mountPath: /tmp/ro-tls/
          subPath: robin-secret
          
  volumes:
    - name: tls-sec
      secret:
        secretName: tls-sec
