apiVersion: v1
kind: Secret
metadata:
  name: tls-sec
type: kubernetes.io/tls
data:
  tls.crt: "SDFGHJKLKJHGrtyuioplokijhgfgyhuio-0987654eerfgbhnjmjk,klkjhgvcc"
  tls.key: "SsdfggvDFGHJKLKJHGrtyuioplokijhgfgyhuio-0987654eerfgbhnjmjk,klkjhgvcc"
