apiVersion: v1
kind: Secret
metadata:
  name: tls-sec
type: kubernetes.io/tls
stringData:
  tls.crt: "SDwergfbhrtgbv3FGHJKLKJHGrtyuioplokijhgfgyhuio-0987654eerfgbhnjmjk,klkjhgvcc"
  tls.key: "SsdfggvDFGHJKLKJHGrtyuioplokijhgfgyhuio-0987654eerfgbhnjmjk,klkjhgvcc"
  robin-secret: "hgiegfcviueguighreoiufhewroiuuhf9070rehfiouherduoivh9u3erh"