apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node-app
spec:
  containers:
    - name: node-container
      image: nginx
      imagePullPolicy: Always
  nodeSelector:
    role: worker
