apiVersion: v1
kind: Pod
metadata:
  name: node-ubuntu
  labels:
    app: node-ubuntu
spec:
  containers:
    - name: node-container
      image: ubuntu
      imagePullPolicy: Always
  nodeSelector:
    role: worker
