apiVersion: v1
kind: Pod
metadata:
  name: node-ubuntu
  labels:
    app: node-ubuntu
spec:
  containers:
    - name: node-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello from BusyBox' && sleep 3600"]
      imagePullPolicy: Always
  nodeSelector:
    role: worker
