apiVersion: v1
kind: Pod
metadata:
  name: node-ubuntu
  labels:
    app: node-ubuntu
spec:
  containers:
    - name: node-container
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Hello from BusyBox'; sleep 30; done"]
      imagePullPolicy: Always
  nodeSelector:
    role: worker
