apiVersion: apps/v1
kind: Deployment
metadata:
  name: downward-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downward-rex
  template:
    metadata:
      labels:
        app: downward-rex
    spec:
      containers:
        - name: downward-api
          image: nginx
          volumeMounts:
            - name: downward-api-volume
              mountPath: /tmp/pod_info
      volumes:
        - name: downward-api-volume
          downwardAPI:
            items:
              - path: "pod-name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "pod-ip"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "pod-namespace"
                fieldRef:
                  fieldPath: metadata.namespace
              - path: "pod-annotations"
                fieldRef:
                  fieldPath: metadata.U
