apiVersion: apps/v1
kind: Deployment
metadata:
  name: vol-res-app
  labels:
    app: vol-res-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vol-res-app
  template:
    metadata:
      name: vol-res-app
      labels:
        app: vol-res-app
    spec:
      containers:
        - name: vol-res-app
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: vol-res-volume
              mountPath: /tmp/rex
      volumes:
        - name: vol-res-volume
          
