apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
spec:
  replicas: 1
  template:
    metadata:
      name: 
    spec:
      containers:
        - name: nginx-webapp
          image: nginx
        - name: busybox
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "echo '<h1>Helllo Worls ingress </h1>' > /usr/share/nginx/html/index.html"]
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          emptyDir: {}
         