apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-webapp

  template:
    metadata:
      labels:
        app: nginx-webapp

    spec:
      initContainers:
      - name: create-index
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "<h1>Hello World Ingress</h1>" > /usr/share/nginx/html/index.html
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html

      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html

      volumes:
      - name: nginx-html
        emptyDir: {}