apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ5b3VyLWRvY2tlci11c2VybmFtZSIsInBhc3N3b3JkIjoieW91ci1kb2NrZXItcGFzc3dvcmQiLCJlbWFpbCI6Im5vbmVAZXhhbXBsZS5jb20iLCJhdXRoIjoiYUdWwVlXTjBlWEJzWVd4MVoyVmZjbVZwZEdGMGFXOXUifX19
type: kubernetes.io/dockerconfigjson
