apiVersion: v1
kind: Secret
metadata:
  name: 
type: kubernetes.io/dockerconfigjson
data:
    dockerUsername: "robin113x"
    dockerPassword: "hwdvchiwdvecihvweihv"
    dockerEmail: "robin113x@gmail.com"
    dockerRegistry: "docker.io"
