apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mysecret
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
