apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sd
spec:
  selector:
    matchLabels:
      app: sd
  template:
    metadata:
      labels:
        app: node-daemonset
    spec:
      containers:
        - name: node-container
          image: h
          imagePullPolicy: Always